### ISSUE TITLE
"Insert literature note link" command places cursor at the beginning of the inserted text instead of the end

### ISSUE THREAD

**Issue by Ikaxas1** [hans/obsidian-citation-plugin#138]
**Describe the bug**
When I use the "Insert literature note link" command, it should insert the string "[[@citekey]]" and then place the cursor *after* that string (I.e.: [[@citekey]]<cursor>). Instead, it inserts that string and then places the cursor *before* the string (i.e.: <cursor>[[@citekey]]).

**To Reproduce**
1. Activate the "Insert literature note link" command (via the command palette or a previously set hotkey).
2. Select a source to insert a link to. 
3. When the link is inserted, the cursor will appear before the inserted string, not after as expected. 

**Platform**
 - OS: Ubuntu 20.04
 - Obsidian version v0.13.19
 - Plugin version 0.4.4

**Additional context**
The behavior here used to be correct (I don't remember exactly when it started, but I think within the past few months). I thought it might have to do with the new "live preview" mode for the Obsidian editor, but the bug remains even when I turn that off. (Maybe it has to do with some backend changes made to facilitate the live preview mode?)

**Comment by Klemet** [comment]
Apparently, this can be corrected by changing the function `replaceRange` by `replaceSelection` at the end of the functions that insert the text (e.g. [here](https://github.com/hans/obsidian-citation-plugin/blob/51934790436ac0f7b6ce4122b9efbd695e6a203b/src/main.ts#L399)). At least, it's working when directly editing `main.js` in this way.

I think this might be due to an update to how the function works in code mirror (see [here](https://github.com/codemirror/dev/issues/586) ?); but I'm not so sure.

**Comment by hans** [comment]
Thanks for the report and @Klemet for the solution!
