### ISSUE TITLE
Loaded library but nothing shows up in Obsidian

### ISSUE THREAD

**Issue by Googlehupf** [hans/obsidian-citation-plugin#163]
**Observed behavior**
The plugin settings dialog displays "Loaded library with 16 references." But nothing shows up in Obsidian. It makes no difference if a literature note folder is specified or not. It makes no difference how many items are in the library file. It makes no difference if CSL-JSON or BibLaTeX is used.

**To Reproduce**
1. Follow the official setup instructions for the Obsidian Citations plugin.
2. Choose a citation database format. Paste the correct citation database path. Specify a literature notes folder or leave the field empty.
5. Close the plugin settings dialog.

**Console output**
No error messages appear in the console.

**Expected behavior**
After closing the plugin settings dialog, citations should appear in the Obsidian Vault.
If a literature notes folder was specified in the plugin settings dialog, it should be created in the Obsidian Vault.

**Platform**
 - macOS 12.3.1
 - Obsidian version 0.14.6
 - Plugin version 0.4.4

**Additional context**
File paths were carefully checked and are correct. The plugin successfully reads the library file, i.e. the number of items it displays is correct. It does not matter if the library is small or very large.

**Comment by orionpilot** [comment]
`Expected behavior: After closing the plugin settings dialog, citations should appear in the Obsidian Vault.` What do you mean by this? If you are expecting that once the plugin dialog closes, you _instantly_ get a literature note for every item in the library, this is incorrect. The plugin does not work like this. To me it sounds like you have correctly setup the plugin but you have just not yet created a literature note. 

In your vault, if you open the command palette and select the `Citations: Open Literature Note` command, do you get the list of  items from your library? And when you select an item, do you get a literature note created/opened? If so, then the plugin is correctly setup and its working properly. If not, write back and we work from there.  

Side note: `If a literature notes folder was specified in the plugin settings dialog, it should be created in the Obsidian Vault.` I don't think the citations plugin automatically creates the literature note folder. To be safe, create it manually.

**Comment by Googlehupf** [comment]
Thank you, @orionpilot. And forgive my stupidity. It works as you described. Seems I should have been paying more attention when watching those instruction videos.

I'll make a donation to show my appreciation for the product and your support. Sorry for stealing your time.

**Comment by XtremLasagnas** [comment]
Hi,
I currently face a similar issue. Just installed the plugin this morning, and set up the database path and the note folder, console command. I can summon the item list with ctrl + shift + O, but it doesn't create a new note. 

I'm on windows 10. Up to date versions of Obsidian and the plugin.

![image](https://user-images.githubusercontent.com/108294499/176000283-67a69482-ac5d-4cc1-8d58-0cc8014f8973.png)
