### ISSUE TITLE
Citation export file cannot be found

### ISSUE THREAD

**Issue by Masoleno** [hans/obsidian-citation-plugin#197]
I am having an issue where Citations is trying to load the citation database forever. I have tried re-exporting my citations from Zotero, re-installing Citations and rebooting Obsidian itself. I think the issue is that Citations doesn't recognise the file path to my .bib file. I have tried multiple file locations and writing the file path with or without backslashes and forward slashes too. My obsidian vault is on my OneDrive and I have saved the .bib file in the root obsidian folder. 

Whatever I put in the file path field, I get the message "The citation export file cannot be found. Please check the path above".

I tried it with a small BetterBibLaTex file as well, only containing 3 refs, but the issue persisted.
I am on a MacOS Monterey 12.6.  Obsidian version 1.0.0. Citations version 0.4.5. 

Any suggestions?

Thanks.

**Comment by orionpilot** [comment]
From what you are saying, it does look like its the path that's the issue. I think I've seen someone else have a similar issue in here but can't find that issue yet. Since you are on macOS, I think forward slashes are the correct path notation. I have my own vault in OneDrive and the bib file locally so that should not be the issue.

It would help if you could share how the path looks like in Obsidian. Can't really say more without seeing that.

**Comment by Masoleno** [comment]
Solved! As I was replying to your comment I went into "Get Info" for the file to copy the path and when I pasted it in here I realised it's different then what's showing in the "Get Info" window. I.e. the "Get Info" window shows the path as OneDrive > PhD > phd-obsidian which is what I've been typing into Obsidian, but when I copy that and paste it I get /Users/name/Library/CloudStorage/OneDrive/PhD/phd-obsidian. Pasting the latter into the Citations path field works like a charm!

Thank you for your help :)
