### ISSUE TITLE
Can't open the note I searched 

### ISSUE THREAD

**Issue by yuyenda0** [hans/obsidian-citation-plugin#212]
**Describe the bug**
Cannot open the note I searched in the citations database. 

**To Reproduce**
1. Ctrl + Shift + O 
2.1. Searched for the articles I wanted to open (Image 1)
=> Clicked and the note didn't appear (Image 2)
2.2. Meanwhile, if I clicked the articles that appears/listed already, the note would be created (Image 3,4)

**Expected behavior**
The note I searched for would appear/open/be created. 

**Screenshots**
Image 1: 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/123443083/214233979-f2830bc1-c2e2-45eb-ba93-2abee85a5b98.png">
Image 2: 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/123443083/214233999-6d4a6602-0482-4d1d-bdff-fa411a2c2dc2.png">
Image 3: 
<img width="831" alt="image" src="https://user-images.githubusercontent.com/123443083/214233925-d5de8075-d0d9-4d4c-8138-a08af893f262.png">
Image 4:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/123443083/214233948-c407e1f4-1cca-46d0-9c14-6e07e1b68bf5.png">

**Platform**
 - OS: [e.g. OS X 11.5.2]
 - Obsidian version [e.g. 0.12.13]
 - Plugin version [e.g. 0.4.3]

**Comment by orionpilot** [comment]
More information is needed to properly help you, though I have a couple ideas. What _exactly_ is your `CTRL-SHIFT-O` hotkey set to? There may be a conflict between the citations plugin and something else. What happens if you select the `Open literature note` command directly from the command palette instead of the hotkey? Also, what are your citation plugin folder settings (i.e, the paths)?

**Comment by yuyenda0** [comment]
I'm sorry, I thought that hotkey was default. It's Open literature note, and it made no different when I select it directly from the command palette. I don't think the hotkey is conflictual. 

My database path is: /Users/username/Desktop/Documents/Academia Obsidian/My Library.json
Literature note folder is just "Zotero" 
<img width="529" alt="image" src="https://user-images.githubusercontent.com/123443083/214341210-740f9449-24f6-42f6-8781-f07e9f9daf54.png">

**Comment by orionpilot** [comment]
The hotkey may have been the default, but since it can be changed, that was one idea I had. I think its also possible that multiple plugins could have the same default hotkey. This was why I asked if you could replicate the issue by selecting that command directly, rather than through the hotkey. I agree it looks like that’s not the issue. 

Thanks for sharing the settings. Since you can see the list of papers from the screenshots you shared, it looks like your database is being properly loaded. Initially, I thought that your settings looked fine but then I think I replicated the issue. Is there an extra space in the folder name “Zotero”? It would look fine without clicking into the textbox. 

Having `Zotero ` in the settings but `Zotero` being the actual folder name can cause this error. I got the error you got by adding an extra space at the end of my literature note folder setting.

**Comment by yuyenda0** [comment]
Thank you. I've checked the extraspace before, but there's none.

**Comment by orionpilot** [comment]
Oh that's interesting. If that's the case, I am not entirely sure what is the source of this problem. My guess is that its _something_ else in your particular vault for some reason. One idea to help troubleshoot: create a new vault on your computer and _only_ setup the citations plugin. If the issue persists, my guess is that its your database somehow that's the issue. If the issue does _not_ persist, then I am pretty sure that the issue is caused by something else in your vault/on your computer. Try adding things back slowly in the new vault and see if the issue pops up again. That should help figure out the culprit.

**Comment by yuyenda0** [comment]
Thank you very much for your help. Anyway, I've resorted to the last available option, which is to change the citation database format (from CSL-JSON to BibLaTex) and now it's working just fine. I guess the issue can be closed for now.
