### ISSUE TITLE
Citation doesn't recognize database path 

### ISSUE THREAD

**Issue by reADwwt** [hans/obsidian-citation-plugin#227]
**Describe the bug**
Starting from this morning, Obsidian has been having trouble locating my literature note folder, which is the same folder that I have been using for more than a year with no trouble. When I try to open a literature note from the navigation interface, it throws a message at me that says "Unable to access literature note. Please check that the literature note folder exists, or update the Citations plugin settings". After I try to add a literature note after the message disappears, nothing happens. And after I close and reopen Obsidian and try to add a literature note again, the same message pops up. 

Suggestions that I have tried but didn't work: 

1. change the "Citation database path" to a different folder with shorter directory 
2. change the json database that I have been using 
3. uninstall and reinstall the Citation plugin 

Until the issue occurred, I had not made any system changes or updating Obsidian or anything 

Also when I change the citation database path or the json file, the editor interface for the plugin shows this message that "loaded library with xxx references", suggesting to me that the path/file is recognized. But for some wierd reason, it is not recognizing the path or file when I need to add a literature note to my note 

**To Reproduce**
1. open literature note
2. pick a note and press enter

**Console output**
not sure how to do this 

**Expected behavior**

**Screenshots**
![test](https://user-images.githubusercontent.com/50057595/232097420-8e0238a5-fc70-4662-964e-8ae45aa2fda5.jpeg)

**Platform**
 - OS: [e.g. OS X 11.5.2]
 - Obsidian version [e.g. 0.12.13]
 - Plugin version [e.g. 0.4.3]

**Additional context**
The citation database path and the json file are the ones that I have been using for over a year with no trouble previously at all

**Comment by orionpilot** [comment]
I agree this does look a bit weird. For reference, to access the console its `ctrl-shift-i` on Windows. I think that means its `cmd-shift-i` on macOS (or whatever the equivalent to `ctrl` is). 

It does look like the _citation database_ path is fine (since its recognizing the XXX entries). But what about the _literature note_ path? There are two different paths in the settings and it looks like you only focused on the first one. Since you say that everything was working fine for a long time, maybe some other process changed the literature note path/folder name. Double check if _that_ path is correct and see if the error persists if that path is blank (so that the notes appear in the root and as a check that its that path that's the issue).

**Comment by reADwwt** [comment]
For the literature note folder, I previously just used the default "Reading Notes" as the folder name. I just changed it to some other names and created folders accordingly. But again none of the new folders worked. But after I deleted the folder name and left the literature note folder blank, it worked and I can now open literature note without getting that annoying message. 

Still not sure what happened but it looks like the problem is resolved. Thanks!
