### ISSUE TITLE
Plugin is useless

### ISSUE THREAD

**Issue by fatkc** [hans/obsidian-citation-plugin#261]
**Describe the bug**
The plugin is unfortunately useless! I'm writing a literature review in Obsidian for the first time, was trying to find some good citation plugins and happened upon this one. Unfortunately, though, it seems to be useless

**To Reproduce**
1. Install the plugin
2. Use any of the five actions in the Command Palette
3. Export to PDF
4. Observe uselessness

**Expected behavior**
I had expected the plugin to be useful. I had anticipated that a citation plugin that was able to interface with my Zotero library would be able to help me to insert citations within my literature review, and have them linked to the Bibliography section within the same .md file.

**Platform**
 - OS: Microsoft Windows 11 Home
 - Obsidian version 1.4.16
 - Plugin version 0.4.5

**Comment by tmuftee** [comment]
Hi, I am not a developer or contributor but I have been using this plugin for 2 years now. I think you may be unsure about workflows. This plugin is very limited in terms of capabilities, it does not form a live link with existing biblio tools like Zotero etc. What it does allow is creation of notes based on records from a .bib file. It does not generate bibliography. However, this is my wokflow from Endnote to Obisidian and then to Word to have a coherent writing process.

1. Generate .bib file from EndNote (this needs to be updated and overwritten manually once in a while)
2. Set up Citations plugin to read the .bib file
3. Create literature source notes with a fixed template (using author name, DOI, year etc.
4. Write paper/report in obisidian creating links to literature source notes
5. Literature source notes created by Citations plugin are named in a way that makes it easier for Word/Endnote plugin to create a proper reference section and make editing/publishing easy. For example in Obsidian I name my notes as {[[LastName RN]]} where RN is the record number from Endnote (I set up a custom output style in Endnote to save RN numbers inside my .bib file). The { } symbols are important.
6. Example in writing. "I agree with the opinion by {[[LastName RN]]} whereas disagree with {[[LastName2 RN2]]}
7. While exporting to word the [[ ]] signs are eliminated using Pandoc plugin. It's a one click process
8. After opening the Word file, I use the EndNote toolbar to refresh references. It picks up the citations easily because of the { } symbols and the RN number, in the end generating a live reference list.
9. Optional: Because I write a lot of drafts without exporting to Word, I use Dataview plugin to create my own references at the end of the notes. It detects the notes linked inside MD file with the tag #bibliography and generates a formatted reference list. All my literature source notes include a custom field containing the formatted citation (APA style)

Hope it helps. I also wish Citations plugin was more capable and automated a lot of the writing stuff but now I am happy with my workflow and have not faced issues in writing.

**Comment by FeralFlora** [comment]
> Export to PDF

Nowhere does this plugin claim to have anything to do with PDF exports, so that mismatch of expectations is entirely on you.

To export to PDF with formatted citations and a bibliography, use a plugin that integrates with [Pandoc](https://pandoc.org/), like [Enhancing export](https://github.com/mokeyish/obsidian-enhancing-export). 

This will format your citekeys, inserted by Citations / Zotero Integration / Zotlit / Pandoc Reference List (doesn't really matter which one you use, so long as you cite using citekeys) according to your desired citation style, and produce a bibliography. See the [Pandoc docs](https://pandoc.org/MANUAL.html#citations) on how to configure it to process citations.

**Comment by Flecart** [comment]
This can be closed I think

**Comment by fatkc** [comment]
> Hi, I am not a developer or contributor but I have been using this plugin for 2 years now. I think you may be unsure about workflows. This plugin is very limited in terms of capabilities, it does not form a live link with existing biblio tools like Zotero etc. What it does allow is creation of notes based on records from a .bib file. It does not generate bibliography. However, this is my wokflow from Endnote to Obisidian and then to Word to have a coherent writing process.
> 
> 1. Generate .bib file from EndNote (this needs to be updated and overwritten manually once in a while)
> 2. Set up Citations plugin to read the .bib file
> 3. Create literature source notes with a fixed template (using author name, DOI, year etc.
> 4. Write paper/report in obisidian creating links to literature source notes
> 5. Literature source notes created by Citations plugin are named in a way that makes it easier for Word/Endnote plugin to create a proper reference section and make editing/publishing easy. For example in Obsidian I name my notes as {[[LastName RN]]} where RN is the record number from Endnote (I set up a custom output style in Endnote to save RN numbers inside my .bib file). The { } symbols are important.
> 6. Example in writing. "I agree with the opinion by {[[LastName RN]]} whereas disagree with {[[LastName2 RN2]]}
> 7. While exporting to word the [[ ]] signs are eliminated using Pandoc plugin. It's a one click process
> 8. After opening the Word file, I use the EndNote toolbar to refresh references. It picks up the citations easily because of the { } symbols and the RN number, in the end generating a live reference list.
> 9. Optional: Because I write a lot of drafts without exporting to Word, I use Dataview plugin to create my own references at the end of the notes. It detects the notes linked inside MD file with the tag #bibliography and generates a formatted reference list. All my literature source notes include a custom field containing the formatted citation (APA style)
> 
> Hope it helps. I also wish Citations plugin was more capable and automated a lot of the writing stuff but now I am happy with my workflow and have not faced issues in writing.

Much appreciated boss, thank you for taking the time! This was very helpful. Dataview is a shout, will figure it out some time !

**Comment by fatkc** [comment]
> > Export to PDF
> 
> Nowhere does this plugin claim to have anything to do with PDF exports, so that mismatch of expectations is entirely on you.
> 
> To export to PDF with formatted citations and a bibliography, use a plugin that integrates with [Pandoc](https://pandoc.org/), like [Enhancing export](https://github.com/mokeyish/obsidian-enhancing-export).
> 
> This will format your citekeys, inserted by Citations / Zotero Integration / Zotlit / Pandoc Reference List (doesn't really matter which one you use, so long as you cite using citekeys) according to your desired citation style, and produce a bibliography. See the [Pandoc docs](https://pandoc.org/MANUAL.html#citations) on how to configure it to process citations.

Thank you very much for this, I'll check it out. You're correct about the mismatch of expectations, admittedly I am a casual with Obsidian. Thank you again for taking the time!

**Comment by fatkc** [comment]
> This can be closed I think

Agreed
