### ISSUE TITLE
{{zoteroSelectURI}} doesn't seem to work as a literature note title template

### ISSUE THREAD

**Issue by akshay1992** [hans/obsidian-citation-plugin#29]
Hey! My intention was to generate a citekey as a markdown link that opens zotero. So I tried setting the _Literature note title template_ in the plugins to the following:
```
 [@{{citekey}}]({{zoteroSelectURI}})
```
When I try to run the "Insert Citation" command, it doesn't seem to do anything. Trying it with just the zotero URI doesn't seem to work. However if I put in `citekey` or any other field in the following, it shows up: 
```
{{zoteroSelectURI}}
```

**Comment by hans** [comment]
Hi, I'm pretty sure the problem is that the literature note titles are going to contain illegal characters (from the Zotero URI). There is indeed a bug, then, that no error is displayed when you try to insert a literature note.

However, it seems like you can get this working now with a different feature -- use the "Insert Markdown citation" command, which allows you to insert an arbitrary citation link, formatted however you desire, without creating a literature note.

The command "Insert Markdown citation" is available via the command palette but has no hotkey set by default; you can configure the template for the inserted citation text at the bottom of the Citations preferences tab.

Hope that helps!

**Comment by akshay1992** [comment]
Thanks, this works!
