### ISSUE TITLE
Can't insert references on MacOS/BibLatex

### ISSUE THREAD

**Issue by gbeine** [hans/obsidian-citation-plugin#82]
Obisidan: 0.11.3
Current version of plugin
macOS: 11.3

BibTex file is loaded, Ctrl-Shift-E and Ctrl-Shift-0 show the entry, but it's not possible to insert it.

![Screenshot 2021-05-06 at 20 01 46](https://user-images.githubusercontent.com/2093685/117345798-40828880-aea7-11eb-9f30-a6accaa3c99b.png)

![Screenshot 2021-05-06 at 20 11 23](https://user-images.githubusercontent.com/2093685/117345810-437d7900-aea7-11eb-8ecc-eb315bc7e93c.png)

**Comment by rachel-1** [comment]
I had the same issue on Windows with a fresh install. It turned out I needed to install [Better Bibtex](https://retorque.re/zotero-better-bibtex/) for Zotero to get the error messages to go away. Maybe that will help?

Granted, it still doesn't do anything when I try to open the literature note link or view PDF. Viewing in Zotero, inserting the literature note content, and inserting the Markdown citation seem to work as intended.

Obisidan: 0.12.3
Current version of plugin
Windows 10: 10.0.19041

**Comment by gbeine** [comment]
@rachel-1 Yepp, that was the issue.
Re-Installing the Better Bibtex Plugin in Zotero fixed the output and afterwards it worked properly!
